Residual Calculation Fix and Miscellaneous Improvements
pberkes/big_O pull request #45
Opened 2022-08-21 20:48 UTC by TheMatt2

Fixes an issue with how residuals are calculated and improves the reliability of test cases.

## Residual Calculation Fix

### tl;dr

The residual value returned from `np.linalg.lstsq(x, y, rcond=-1)` for Polynomial and
Exponential classes can not be meaningfully compared with the other complexity classes.

https://github.com/pberkes/big_O/blob/0ed1e3d2d4a74f3c2f41bb6b147d4a2231f8fcb3/big_o/complexities.py#L36

The issue is the transform used in Polynomial and Exponential complexity classes to correctly
generate the coefficients causes the residual calculation to be invalidated.

https://github.com/pberkes/big_O/blob/0ed1e3d2d4a74f3c2f41bb6b147d4a2231f8fcb3/big_o/complexities.py#L189-L190

The solution is to recalculate the residuals manually:
```python
ref_t = self.compute(n)
residuals = np.sum((ref_t - t) ** 2)
```
### Steps to Reproduce

Here is an example that demonstrates big_O misclassifying a quadratic function because of this issue.

```python
import big_o
import numpy as np
import matplotlib.pyplot as plt

# Set seed for consistent results
rng = np.random.default_rng(1234)

measures = np.linspace(1, 10, 100)

# Quadratic Function
func = lambda x: x**2

# Add randomness so its not exactly a quadratic
times = func(measures + np.abs(rng.standard_normal(measures.size)) * .1) + np.abs(rng.standard_normal(measures.size))

# Run big_o to get the best result
best, fitted = big_o.infer_big_o_class(measures, times, verbose = True)
# Observe best is *not* quadatic

# Lookup the fitted function for quadratic and exponential
quadatic = next(complexity for complexity in fitted if isinstance(complexity, big_o.complexities.Quadratic))
exponential = next(complexity for complexity in fitted if isinstance(complexity, big_o.complexities.Exponential))

# Plot the "best", second best, and the actual solution
plt.plot(measures, times, "-", label = "Original")
plt.plot(measures, best.compute(measures), "--", label = "Best " + str(best))
plt.plot(measures, quadatic.compute(measures), "--", label = quadatic)
plt.plot(measures, exponential.compute(measures), "--", label = exponential)
plt.xlabel("n")
plt.ylabel("t (sec)")
plt.legend()
plt.show()
```

```
Constant: time = 39 (sec) (r=90378.409421)
Linear: time = -23 + 11*n (sec) (r=4052.834495)
Quadratic: time = 1.2 + 1*n^2 (sec) (r=89.693176)
Cubic: time = 10 + 0.1*n^3 (sec) (r=2269.462214)
Polynomial: time = 1.6 * x^1.8 (sec) (r=1.323089)
Logarithmic: time = -30 + 45*log(n) (sec) (r=19352.077840)
Linearithmic: time = -4.4 + 4.3*n*log(n) (sec) (r=1389.322845)
Exponential: time = 2.8 * 1.5^n (sec) (r=6.137839)
```

As for can see in the calculated residuals, the best matching functions should be Polynomial with a residual of `1.32`, followed by Exponential with a residual of `6.14`, and followed distantly by Quadratic with a residual `89.70`.
This is surprising, since the original function is Quadratic, yet Polynomial and Exponential were found to be better matches.

If we look at the graph, we can see this is an issue.

![Big O Graph Demonstrating Classification Bug](https://user-images.githubusercontent.com/22862051/185802748-ec68955d-71b7-4d5d-94d2-1bae137021df.png)

Blue is the original function.
Green is the Quadratic complexity, which seems to match the original input quite well.
Orange is the Polynomial complexity, which seems to trail off of the original function at the tail end.
Red is Exponential complexity, which does not seem to match the original function very well at all, yet had a lower residual than Quadratic.

This is an issue. `big_o.infer_big_o_class` should have identified Quadratic as the best complexity.

### The Math
```python
coeff, residuals, rank, s = np.linalg.lstsq(x, y, rcond=-1)
```

$n_i$ is the input measurement ($i$ is the index for multiple measurements)

$t_i$ is the time measured for the cooresponding $n_i$

For each complexity, there are functions $F(n_i)$ and $T(t_i)$ that transforms $n_i$
and $t_i$ before they are passed to `np.linalg.lstsq()`.

The result of `np.linalg.lstsq()` are `coeff`, which is referenced as $c$ and `residuals`
which is referenced at $r$.

The other outputs from `np.linalg.lstsq()` are unused.

$$x_i = F(n_i)$$
$$y_i = T(t_i)$$

| Complexity   |   $F(n)$ |  $T(t)$ | $T^-1(t')$ |
|--------------|----------|---------|-----------|
| Constant     |      $1$ |     $t$ |       $t$ |
| Linear       |      $n$ |     $t$ |       $t$ |
| Quadratic    |    $n^2$ |     $t$ |       $t$ |
| Cubic        |    $n^3$ |     $t$ |       $t$ |
| Logarithmic  |  $ln(n)$ |     $t$ |       $t$ |
| Linearithmic | $nln(n)$ |     $t$ |       $t$ |
| Polynomial   |  $ln(n)$ | $ln(t)$ |     $e^t$ |
| Exponential  |      $n$ | $ln(t)$ |     $e^t$ |

The residual from `np.linalg.lstsq()` is calculated as the sum of squares of the calculated coefficiences.

$$t_i' = c_{1}F(n_i)+c_0$$

This can be expressed by the following equation for a given $F(n_i)$ and $T(t_i)$ with the resulting coefficience $c$:

$$r=\sum_{i=0}^{k}(t_i'-T(t_i))^2$$

_However_ the equation for error, the distance between the equation represented by the complexity and the inputted function is calculated by applying $T^{-1}(t')$ to $t_i'$ instead of applying $T(t)$ to $t_i$.

$$s=\sum_{i=0}^{k}(T^{-1}(t_i')-t_i)^2$$

For must of the complexity functions, where $T(t) = t$, this error calculation is equal to the residual calculation.

But these are not equal for Polynomial and Exponential. This is shown in the table below:

<br></br>

| Complexity   | Residual                           | Error                              | Residual = Error |
|--------------|------------------------------------|------------------------------------|------------------|
| Constant     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Linear       | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Quadratic    | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Cubic        | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Logarithmic  | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Linearithmic | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | $$\sum_{i=0}^{k}(t_i'-t_i)^2$$     | ✅               |
| Polynomial   | $$\sum_{i=0}^{k}(t_i'-ln(t_i))^2$$ | $$\sum_{i=0}^{k}(e^{t_i'}-t_i)^2$$ | ❌               |
| Exponential  | $$\sum_{i=0}^{k}(t_i'-ln(t_i))^2$$ | $$\sum_{i=0}^{k}(e^{t_i'}-t_i)^2$$ | ❌               |

So for Polynomial and Exponential, the residual must be recalculated to be equal to the error.

## Test Cases Improvements

From testing, it seems that specifically the test `big_o.test.test_big_o.TestBigO` seems to fail often.

```
% python -m unittest -v
test_big_o (big_o.test.test_big_o.TestBigO) ... FAIL
test_big_o_return_raw_data_default (big_o.test.test_big_o.TestBigO) ... ok
test_big_o_return_raw_data_false (big_o.test.test_big_o.TestBigO) ... ok
test_big_o_return_raw_data_true (big_o.test.test_big_o.TestBigO) ... ok
test_infer_big_o (big_o.test.test_big_o.TestBigO) ... ok
test_measure_execution_time (big_o.test.test_big_o.TestBigO) ... ok
test_compute (big_o.test.test_complexities.TestComplexities) ... ok
test_not_fitted (big_o.test.test_complexities.TestComplexities) ... ok
test_str_includes_units (big_o.test.test_complexities.TestComplexities) ... ok
test_eq (big_o.test.test_complexityclass_comparisons.TestComplexities) ... ok
test_g (big_o.test.test_complexityclass_comparisons.TestComplexities) ... ok
test_ge (big_o.test.test_complexityclass_comparisons.TestComplexities) ... ok
test_l (big_o.test.test_complexityclass_comparisons.TestComplexities) ... ok
test_le (big_o.test.test_complexityclass_comparisons.TestComplexities) ... ok

======================================================================
FAIL: test_big_o (big_o.test.test_big_o.TestBigO)
--------------------------------------------------------- [...]

2022-08-22 15:52 UTC, pberkes commented
Hi @TheMatt2 ! Thank you for the PR and the thorough description, I'll have a look as soon as possible.

In the meantime, the description of the first part seems similar to a previous issue that you fixed in #44 , would you mind explaining the difference in short?

2022-08-23 00:54 UTC, TheMatt2 commented
Hi @pberkes !

Apologize, I realize this is quite a lengthy PR. The is a somewhat subtle bug, but actually has a significant impact on the classification accuracy, so I wanted to make sure to include a mathematical breakdown.

This is similar to PR #44 in that both issues deal with the implement of `Polynomial` and `Exponential` complexities and correctly accounting for the logarithmic transform that these complexities use that the other complexities don't.


The difference is PR #44 is a fix for `Complexity.compute()`, while this PR is a fix for `Complexity.fit()`

Unlike PR #44, this PR actually changes the behavior of how bigo decides the classification of a given function.

2022-09-01 18:09 UTC, TheMatt2 commented
Update on this?

2022-09-04 09:13 UTC, pberkes commented
I'm sorry, @TheMatt2 , I've been traveling, I'll have a look this week

2022-09-05 10:06 UTC, pberkes commented
Hi @TheMatt2 , thanks for the PR! Good catch with the residuals, and the Python optimization problem is fun.
This PR is fixing 3 separate issues, in the future please submit each in a separate PR for faster review.

My main concern is that if I set `_recalculate_residuals = False` in `Polynomial` and `Exponential`, all tests still pass. Could you please add a test that would fail without `_recalculate_residuals`?

As for design, I'm not a big fan of having that behavior controlled by a class attribute. The solutions I propose are 1) recalculate the residuals always; there's some overhead but it's the cleanest; or 2) define a method `_compute_fit_residuals(n, t, lstsq_residuals)` whose basic implementation is `return lstsq_residuals[0]`. What do you think? I'm open for discussion on this point.

I'll add other minor comments online

2022-09-05 10:17 UTC, pberkes requested changes

2022-09-05 10:17 UTC, pberkes commented on big_o/complexities.py
> +    _recalculate_residuals = False
if we go with this solution, I suggest to rename to `_recalculate_fit_residuals` and add a docstring (a comment formatted with `#: description` above the variable)

2022-09-05 10:17 UTC, pberkes commented on big_o/test/test_big_o.py
> +def dummy_constant_function(n):
Small formatting issue: two spaces `\n\n` between functions

2022-09-05 10:17 UTC, pberkes commented on big_o/test/test_big_o.py
> +                    self.skipTest("Complexity fit error is too high to be reliable (and test failed)")
I think the test should fail in both cases, with the error messages you wrote
(i.e., use `self.fail` instead of `self.skipTest`)

2022-09-06 17:57 UTC, TheMatt2 commented
Hi @pberkes ,

Apologize for lumping multiple issues into this 1 PR, in hindsight, I should have used branches to track the changes separately. Now I know for next time.

I follow using `_recalculate_residuals` may seem a bit counter-intuitive. I wanted to avoid creating a dedicated internal function for this purpose, as it could imply that each class should have a different implementation, like `_transform_n()`.
However, there are only the two ways to calculate residuals:

1) Using the result of `np.linalg.lstsq()`
2) `residuals = np.sum((ref_t - t) ** 2)`

To denote that the correct behavior is only going to be one of these two behaviors, I thought a class level boolean value would be appropriate.

Technically, the code could check if `ComplexityClass._transform_time()` has been overridden and use that to determine the behavior, but I don't think that would be preferable.

Obviously always recalculating residuals solve this problem, but it seems a waste to always redo the calculation when the majority of complexity classes can just use the value from `np.linalg.lstsq()`. Best that I can see there is no way to have numpy compute the coefficients without a residuals calculation.

I think keeping it as a class variable would be best, though I accept your recommendation to name it `_recalculate_fit_residuals`.

Might be worth acknowledge that there is another option to explicitly override `fit()` in the subclasses.

```python
class Polynomial(ComplexityClass):
    def fit(self, n, t):
        """ Fit complexity class parameters to timing data.

        Input:
        ------

        n -- Array of values of N for which execution time has been measured.

        t -- Array of execution times for each N in seconds.

        Output:
        -------

        residuals -- Sum of square errors of fit
        """
        # Explicitly calculate residuals
        # Time transform means residuals isn't comparable
        super().fit(n, t)
        ## Alternatively
        # ComplexityClass.fit(self, n, t)
        ref_t = self.compute(n)
        residuals = np.sum((ref_t - t) ** 2)
        return residuals
```

2022-09-06 17:58 UTC, TheMatt2 commented
As for the test cases passing even if `_recalculate_residuals = False`, I will look into this.
The point of the test cases changes is so they would no pass in this situation.

2022-09-06 19:07 UTC, TheMatt2 commented
I am unable to replicate the tests passing when  `_recalculate_residuals = False`

When I run the test set I (correctly) get the failure message:

```
(venv) big_O % python -m unittest 
.......F........
======================================================================
FAIL: test_compute (big_o.test.test_complexities.TestComplexities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "big_O/big_o/test/test_complexities.py", line 35, in test_compute
    assert_allclose(residuals, np.sum((y - ref_y) ** 2), rtol=1e-07, atol=1e-08,
  File "big_O/venv/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "big_O/venv/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-08
compute() residuals failed to match expected values for class <class 'big_o.complexities.Exponential'>
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 3.25244183e+70
Max relative difference: 1.
 x: array(6.265939e-27)
 y: array(3.252442e+70)

----------------------------------------------------------------------
Ran 16 tests in 45.164s

FAILED (failures=1)
```

This failure is expected if residual calculation was not performed correctly.
Would you mind adding some detail of the circumstance that the test passes?

Note that this test directly calls `ComplexityClass.fit()` and `Complexity.compute()` so this should not change with timing variations between systems.

2022-09-09 07:47 UTC, pberkes commented
The test case for `Exponential` fails when you set `_recalculate_residuals` to False, but not the one for `Polynomial`

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/314633/189299393-b030cabf-8d04-493f-8980-7df942c5ec24.png">

2022-09-09 07:48 UTC, pberkes commented
I'm ok with renaming `_recalculate_fit_residuals` and going with your current solution

2022-09-10 19:13 UTC, TheMatt2 commented
I see you are correct. Good catch.

Apologize, I had thought I had tested that, but I guess I accidentally tested the Exponential case.

For the test case, the answer for Polynomial with `_recalculate_residuals = False` is off by 10 orders of magnitude, but is so close to 0, that the check doesn't catch it. Will fix. Oops.

```python
>>> class_
<class 'big_o.complexities.Polynomial'>
>>> np.sum((y - ref_y) ** 2)
5.0832678484432925e-18
>>> residuals
1.7620118668727588e-28
```

2022-09-12 01:36 UTC, TheMatt2 reviewed
I think that covers all requested changes.
Let me know if there is anything else you would like me to change.

2022-09-12 13:24 UTC, pberkes commented
LGTM, thank you!

2022-09-12 13:24 UTC, merged

2023-05-26 10:18 UTC, DanielHabenicht commented
Thanks everybody for providing this fix! I was going down the same rabbit hole as @TheMatt2 and wondering why it would not classify my linear values as a linear complexity class, but as polynomial instead. 

The culprit now is: This was never released to a current big-O pip package, so everybody might still be running into this problem (just like I am). Is there a timeline on when the next release is due @pberkes ? (I can see there is https://github.com/pberkes/big_O/issues/46)